-- MySQL Script generated by MySQL Workbench
-- Mon May 10 13:42:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema e-commerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema e-commerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e-commerce` DEFAULT CHARACTER SET utf8 ;
USE `e-commerce` ;

-- -----------------------------------------------------
-- Table `e-commerce`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-commerce`.`admin` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `count` INT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`idadmin`),
  UNIQUE INDEX `idadmin_UNIQUE` (`idadmin` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-commerce`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-commerce`.`customer` (
  `idcustomer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `count` INT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`idcustomer`),
  UNIQUE INDEX `idcustomer_UNIQUE` (`idcustomer` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-commerce`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-commerce`.`product` (
  `idproduct` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DOUBLE NOT NULL,
  `description` VARCHAR(245) NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `discount` DOUBLE NOT NULL,
  `total` DOUBLE NOT NULL,
  `image` VARCHAR(245) NOT NULL,
  `thumbnail` VARCHAR(245) NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`idproduct`),
  UNIQUE INDEX `idproduct_UNIQUE` (`idproduct` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-commerce`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-commerce`.`address` (
  `idaddress` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `postal_code` VARCHAR(45) NOT NULL,
  `customer_idcustomer` INT NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idaddress`, `customer_idcustomer`),
  UNIQUE INDEX `idaddress_UNIQUE` (`idaddress` ASC) VISIBLE,
  INDEX `fk_address_customer1_idx` (`customer_idcustomer` ASC) VISIBLE,
  CONSTRAINT `fk_address_customer1`
    FOREIGN KEY (`customer_idcustomer`)
    REFERENCES `e-commerce`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-commerce`.`product_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-commerce`.`product_image` (
  `idproduct_image` INT NOT NULL AUTO_INCREMENT,
  `image_name` VARCHAR(45) NULL,
  `image_url` VARCHAR(45) NULL,
  `image_type` VARCHAR(45) NULL,
  `product_idproduct` INT NOT NULL,
  PRIMARY KEY (`idproduct_image`, `product_idproduct`),
  UNIQUE INDEX `idproduct_image_UNIQUE` (`idproduct_image` ASC) VISIBLE,
  INDEX `fk_product_image_product1_idx` (`product_idproduct` ASC) VISIBLE,
  CONSTRAINT `fk_product_image_product1`
    FOREIGN KEY (`product_idproduct`)
    REFERENCES `e-commerce`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-commerce`.`product_rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-commerce`.`product_rating` (
  `idproduct_rating` INT NOT NULL AUTO_INCREMENT,
  `star_rating` INT NULL,
  `review` VARCHAR(45) NULL,
  `product_idproduct` INT NOT NULL,
  PRIMARY KEY (`idproduct_rating`, `product_idproduct`),
  UNIQUE INDEX `idproduct_rating_UNIQUE` (`idproduct_rating` ASC) VISIBLE,
  INDEX `fk_product_rating_product1_idx` (`product_idproduct` ASC) VISIBLE,
  CONSTRAINT `fk_product_rating_product1`
    FOREIGN KEY (`product_idproduct`)
    REFERENCES `e-commerce`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-commerce`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-commerce`.`cart` (
  `idcart` INT NOT NULL AUTO_INCREMENT,
  `customer_idcustomer` INT NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL,
  `price` DOUBLE NOT NULL,
  `date` DATE NULL,
  `time` TIME NULL,
  `product_idproduct` INT NOT NULL,
  PRIMARY KEY (`idcart`, `customer_idcustomer`, `product_idproduct`),
  UNIQUE INDEX `idcart_UNIQUE` (`idcart` ASC) VISIBLE,
  INDEX `fk_cart_customer1_idx` (`customer_idcustomer` ASC) VISIBLE,
  INDEX `fk_cart_product1_idx` (`product_idproduct` ASC) VISIBLE,
  CONSTRAINT `fk_cart_customer1`
    FOREIGN KEY (`customer_idcustomer`)
    REFERENCES `e-commerce`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_product1`
    FOREIGN KEY (`product_idproduct`)
    REFERENCES `e-commerce`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-commerce`.`wishlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-commerce`.`wishlist` (
  `idwishlist` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `insertDate` DATE NULL,
  `price` DOUBLE NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  `quantity` VARCHAR(45) NOT NULL,
  `customer_idcustomer` INT NOT NULL,
  PRIMARY KEY (`idwishlist`, `customer_idcustomer`),
  UNIQUE INDEX `idwishlist_UNIQUE` (`idwishlist` ASC) VISIBLE,
  INDEX `fk_wishlist_customer1_idx` (`customer_idcustomer` ASC) VISIBLE,
  CONSTRAINT `fk_wishlist_customer1`
    FOREIGN KEY (`customer_idcustomer`)
    REFERENCES `e-commerce`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-commerce`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-commerce`.`order` (
  `orderid` INT NOT NULL AUTO_INCREMENT,
  `invoice_no` INT NOT NULL,
  `orderDate` DATETIME NULL,
  `amount` DOUBLE NOT NULL,
  `discount` DOUBLE NOT NULL,
  `tax` DOUBLE NOT NULL,
  `netamount` DOUBLE NOT NULL,
  `shippingDate` DATETIME NULL,
  `shippingAddress` VARCHAR(45) NOT NULL,
  `billingAddress` VARCHAR(45) NOT NULL,
  `customer_idcustomer` INT NOT NULL,
  PRIMARY KEY (`orderid`, `customer_idcustomer`),
  UNIQUE INDEX `customer_idcustomer_UNIQUE` (`orderid` ASC) VISIBLE,
  INDEX `fk_order_customer1_idx` (`customer_idcustomer` ASC) VISIBLE,
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`customer_idcustomer`)
    REFERENCES `e-commerce`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-commerce`.`orderItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-commerce`.`orderItem` (
  `idorderItem` INT NOT NULL AUTO_INCREMENT,
  `price` DOUBLE NOT NULL,
  `quantity` INT NOT NULL,
  `discount` DOUBLE NOT NULL,
  `total` DOUBLE NOT NULL,
  `order_orderid` INT NOT NULL,
  `order_customer_idcustomer` INT NOT NULL,
  PRIMARY KEY (`idorderItem`, `order_orderid`, `order_customer_idcustomer`),
  UNIQUE INDEX `idorderItem_UNIQUE` (`idorderItem` ASC) VISIBLE,
  INDEX `fk_orderItem_order1_idx` (`order_orderid` ASC, `order_customer_idcustomer` ASC) VISIBLE,
  CONSTRAINT `fk_orderItem_order1`
    FOREIGN KEY (`order_orderid` , `order_customer_idcustomer`)
    REFERENCES `e-commerce`.`order` (`orderid` , `customer_idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-commerce`.`orderStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-commerce`.`orderStatus` (
  `idorderStatus` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  `time` DATETIME NULL,
  `date` DATETIME NULL,
  `order_orderid` INT NOT NULL,
  `order_customer_idcustomer` INT NOT NULL,
  PRIMARY KEY (`idorderStatus`, `order_orderid`, `order_customer_idcustomer`),
  UNIQUE INDEX `idorderStatus_UNIQUE` (`idorderStatus` ASC) VISIBLE,
  INDEX `fk_orderStatus_order1_idx` (`order_orderid` ASC, `order_customer_idcustomer` ASC) VISIBLE,
  CONSTRAINT `fk_orderStatus_order1`
    FOREIGN KEY (`order_orderid` , `order_customer_idcustomer`)
    REFERENCES `e-commerce`.`order` (`orderid` , `customer_idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-commerce`.`product_FAQ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-commerce`.`product_FAQ` (
  `idproduct_FAQ` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(45) NULL,
  `asnwwer` VARCHAR(45) NULL,
  `product_idproduct` INT NOT NULL,
  PRIMARY KEY (`idproduct_FAQ`, `product_idproduct`),
  UNIQUE INDEX `idproduct_FAQ_UNIQUE` (`idproduct_FAQ` ASC) VISIBLE,
  INDEX `fk_product_FAQ_product1_idx` (`product_idproduct` ASC) VISIBLE,
  CONSTRAINT `fk_product_FAQ_product1`
    FOREIGN KEY (`product_idproduct`)
    REFERENCES `e-commerce`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-commerce`.`orderAddress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-commerce`.`orderAddress` (
  `idorderAddress` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `postal_code` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `order_orderid` INT NOT NULL,
  `order_customer_idcustomer` INT NOT NULL,
  PRIMARY KEY (`idorderAddress`, `order_orderid`, `order_customer_idcustomer`),
  UNIQUE INDEX `idorderAddress_UNIQUE` (`idorderAddress` ASC) VISIBLE,
  INDEX `fk_orderAddress_order1_idx` (`order_orderid` ASC, `order_customer_idcustomer` ASC) VISIBLE,
  CONSTRAINT `fk_orderAddress_order1`
    FOREIGN KEY (`order_orderid` , `order_customer_idcustomer`)
    REFERENCES `e-commerce`.`order` (`orderid` , `customer_idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-commerce`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-commerce`.`ticket` (
  `ticketId` INT NOT NULL AUTO_INCREMENT,
  `createdBy` VARCHAR(245) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL,
  `resolvedBy` VARCHAR(245) NOT NULL,
  `resolvedAt` TIMESTAMP NOT NULL,
  `description` VARCHAR(245) NOT NULL,
  `type` VARCHAR(245) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `admin_idadmin` INT NOT NULL,
  `count` INT NOT NULL,
  PRIMARY KEY (`ticketId`, `admin_idadmin`),
  UNIQUE INDEX `ticketId_UNIQUE` (`ticketId` ASC) VISIBLE,
  INDEX `fk_ticket_admin1_idx` (`admin_idadmin` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_admin1`
    FOREIGN KEY (`admin_idadmin`)
    REFERENCES `e-commerce`.`admin` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
